DROP TABLE IF EXISTS flights;
CREATE TABLE flights (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  session_id INTEGER NOT NULL,
  round INTEGER NOT NULL,
  FOREIGN KEY (session_id) REFERENCES sessions(id)
);
